// @generated by shiplightai v0.1.104+fmt2
import { test, expect } from 'shiplightai/fixture';

test.use({
  "baseURL": "https://static.shiplight.ai"
});

test('Create a new user with Determinisc YAML', async ({ page, agent }) => {
  // Test steps
  // main.0: Navigate to /testing/forms/basic-form.html
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await agent.execAction("go_to_url", page, {
      action_data: { kwargs: { url: "/testing/forms/basic-form.html" } },
    });
  }, "Navigate to /testing/forms/basic-form.html", 'main.0', '34363a49-a34a-3c62-d289-532af4d08894', false);

  // Step: Enter "Bruno Henrique Araujo" in the Full Name field
  // main.1.0: Click on the Full Name input field to focus it
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await page.getByRole('textbox', { name: 'Full Name *' }).first().click({ timeout: 5000 });
  }, "Click on the Full Name input field to focus it", 'main.1.0', '64ad0198-8a4c-e3bd-678b-dda25d320f2d', true);

  // main.1.1: Clear any existing content in the Full Name field
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await agent.execAction("clear_input", page, {
      locator: "getByRole('textbox', { name: 'Full Name *' })",
    });
  }, "Clear any existing content in the Full Name field", 'main.1.1', '9e53443e-00df-9c90-775e-1c007ad743fe', true);

  // main.1.2: Type 'Bruno Henrique Araujo' in the Full Name field
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await agent.execAction("input_text", page, {
      action_data: { kwargs: { text: "Bruno Henrique Araujo" } },
      locator: "getByRole('textbox', { name: 'Full Name *' })",
    });
  }, "Type 'Bruno Henrique Araujo' in the Full Name field", 'main.1.2', 'abd4e4b2-8810-734f-0cea-52360644171a', true);

  // Step: Enter "RuadosQAs@gmail.com" in the Email Address field
  // main.2.0: Click on the Email Address input field
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await page.getByRole('textbox', { name: 'Email Address *' }).first().click({ timeout: 5000 });
  }, "Click on the Email Address input field", 'main.2.0', 'fbe48d02-4ce5-c90e-172a-c32bd8afe18b', true);

  // main.2.1: Clear the existing content in the email field
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await agent.execAction("clear_input", page, {
      locator: "getByRole('textbox', { name: 'Email Address *' })",
    });
  }, "Clear the existing content in the email field", 'main.2.1', 'dafe704e-7e7e-a79e-f477-58a95bb025da', true);

  // main.2.2: Type 'Rua dos QAs' in the Email Address field
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await agent.execAction("input_text", page, {
      action_data: { kwargs: { text: "RuadosQAs@gmail.com" } },
      locator: "getByRole('textbox', { name: 'Email Address *' })",
    });
  }, "Type 'Rua dos QAs' in the Email Address field", 'main.2.2', 'cd735073-156c-167e-86c9-e2c7cd8675bc', true);

  // main.3: Select "01/01/2024" from the Birth Date dropdown
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await agent.execAction("set_date_for_native_date_picker", page, {
      action_data: { kwargs: { date: "2024-01-01" } },
      locator: "getByRole('textbox', { name: 'Birth Date *' })",
    });
  }, "Select \"01/01/2024\" from the Birth Date dropdown", 'main.3', 'ca6d65b3-c201-4ea5-5ff1-7ed8ccc034cd', true);

  // Step: Select "Brazil" from the Country dropdown
  // main.4.0: Click the Country dropdown button to open the country selection menu
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await page.getByRole('button', { name: 'Choose a country' }).first().click({ timeout: 5000 });
  }, "Click the Country dropdown button to open the country selection menu", 'main.4.0', 'a7501317-d321-168a-70c6-685ad7f2fc77', true);

  // main.4.1: Click on the search field to focus it
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await page.getByRole('textbox', { name: 'Search countries...' }).first().click({ timeout: 5000 });
  }, "Click on the search field to focus it", 'main.4.1', '7b886362-8841-caf5-fda6-86176aec20e6', true);

  // main.4.2: Type 'Brazil' in the search field to filter the country list
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await agent.execAction("input_text", page, {
      action_data: { kwargs: { text: "Brazil" } },
      locator: "getByRole('textbox', { name: 'Search countries...' })",
    });
  }, "Type 'Brazil' in the search field to filter the country list", 'main.4.2', 'a7304fdf-c434-306e-d095-04f75c67e0b5', true);

  // main.4.3: Click on Brazil in the dropdown list to select it
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await page.getByText('🇧🇷 Brazil').first().click({ timeout: 5000 });
  }, "Click on Brazil in the dropdown list to select it", 'main.4.3', 'e963f71a-d289-91d3-4e76-b6afd25a0c89', true);

  // Step: Enter "Rua dos QAs" in the Message text area
  // main.5.0: Click on the Message text area to focus it
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await page.getByRole('textbox', { name: 'Message' }).first().click({ timeout: 5000 });
  }, "Click on the Message text area to focus it", 'main.5.0', '71e6c07e-3142-09eb-3928-2f6861619932', true);

  // main.5.1: Type 'Rua dos QAs' into the Message text area
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await agent.execAction("input_text", page, {
      action_data: { kwargs: { text: "Rua dos QAs" } },
      locator: "getByRole('textbox', { name: 'Message' })",
    });
  }, "Type 'Rua dos QAs' into the Message text area", 'main.5.1', '76c176ce-6643-0d5f-2684-f02d97284503', true);

  // main.6: Select "I agree to the Terms and Conditions " check button
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await page.getByRole('checkbox', { name: 'I agree to the Terms and' }).first().click({ timeout: 5000 });
  }, "Select \"I agree to the Terms and Conditions \" check button", 'main.6', '6bb753fa-74f8-8118-24ce-b328aeedc217', true);

  // main.7: Click "Submit Form" button
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await page.getByRole('button', { name: 'Submit Form' }).first().click({ timeout: 5000 });
  }, "Click \"Submit Form\" button", 'main.7', '098eaf70-b00f-4494-e81e-9a09e27abe7d', true);

  // main.8: Code block
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    {
      await expect(page.locator('#form-result')).toContainText('Success!')
    }
  }, "Code block", 'main.8', '0edc260a-7dfc-2389-7611-0c830277e5a9', false);
});