// @generated by shiplightai v0.1.104+fmt2
import { test, expect } from 'shiplightai/fixture';

test.use({
  "baseURL": "https://static.shiplight.ai/"
});

test('Create a new user with Interpreted YAML', async ({ page, agent }) => {
  // Test steps
  // main.0: Navigate to /testing/forms/basic-form.html
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await agent.execAction("go_to_url", page, {
      action_data: { kwargs: { url: "/testing/forms/basic-form.html" } },
    });
  }, "Navigate to /testing/forms/basic-form.html", 'main.0', 'f276c713-e869-614a-ccfb-fb910209f3cb', false);

  // main.1: Enter "Bruno Henrique Araujo" in the Full Name field
  // ⚠ DRAFT: AI-resolved at runtime (~5-10s). Add a locator to make this <1s.
  page = agent.agentServices.validatePage(page);
  await agent.run(page, "Enter \"Bruno Henrique Araujo\" in the Full Name field", 'main.1');

  // main.2: Enter "RuadosQAs@gmail.com" in the Email Address field
  // ⚠ DRAFT: AI-resolved at runtime (~5-10s). Add a locator to make this <1s.
  page = agent.agentServices.validatePage(page);
  await agent.run(page, "Enter \"RuadosQAs@gmail.com\" in the Email Address field", 'main.2');

  // main.3: Select "01/01/2024" from the Birth Date dropdown
  // ⚠ DRAFT: AI-resolved at runtime (~5-10s). Add a locator to make this <1s.
  page = agent.agentServices.validatePage(page);
  await agent.run(page, "Select \"01/01/2024\" from the Birth Date dropdown", 'main.3');

  // main.4: Select "Brazil" from the Country dropdown
  // ⚠ DRAFT: AI-resolved at runtime (~5-10s). Add a locator to make this <1s.
  page = agent.agentServices.validatePage(page);
  await agent.run(page, "Select \"Brazil\" from the Country dropdown", 'main.4');

  // main.5: Enter "Rua dos Test" in the Message text area
  // ⚠ DRAFT: AI-resolved at runtime (~5-10s). Add a locator to make this <1s.
  page = agent.agentServices.validatePage(page);
  await agent.run(page, "Enter \"Rua dos Test\" in the Message text area", 'main.5');

  // main.6: Select "I agree to the Terms and Conditions " check button
  // ⚠ DRAFT: AI-resolved at runtime (~5-10s). Add a locator to make this <1s.
  page = agent.agentServices.validatePage(page);
  await agent.run(page, "Select \"I agree to the Terms and Conditions \" check button", 'main.6');

  // main.7: Click "Submit Form" button
  // ⚠ DRAFT: AI-resolved at runtime (~5-10s). Add a locator to make this <1s.
  page = agent.agentServices.validatePage(page);
  await agent.run(page, "Click \"Submit Form\" button", 'main.7');

  // main.8: Should be displayed "Success! Form submitted successfully."
  page = agent.agentServices.validatePage(page);
  await agent.assert(page, "Should be displayed \"Success! Form submitted successfully.\"", "main.8");
});