// @generated by shiplightai v0.1.104+fmt2
import { test, expect } from 'shiplightai/fixture';

test.use({
  "baseURL": "file:///users/brunoaraujo/Documents/test/"
});

test('Test Shiplight AI Self-Handling', async ({ page, agent }) => {
  // Test steps
  // main.0: Navigate to index.html
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await agent.execAction("go_to_url", page, {
      action_data: { kwargs: { url: "index.html" } },
    });
  }, "Navigate to index.html", 'main.0', 'bfa17190-1c72-143d-170f-3f6ff7f6d078', false);

  // main.1: Preencher o campo Nome com QA Test AI
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await agent.execAction("input_text", page, {
      action_data: { kwargs: { text: "QA Test AI" } },
      locator: "getByPlaceholder('Escreva seu nome aqui')",
    });
  }, "Preencher o campo Nome com QA Test AI", 'main.1', 'cfc943b1-f5f8-63c5-7b00-d8acb0874191', true);

  // main.2: Preencher o campo E-mail com emailQATestAI@gmail.com
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await agent.execAction("input_text", page, {
      action_data: { kwargs: { text: "emailQATestAI@gmail.com" } },
      locator: "getByPlaceholder('exemplo@email.com')",
    });
  }, "Preencher o campo E-mail com emailQATestAI@gmail.com", 'main.2', 'aaff6378-c97a-513b-0a26-05848ea4a686', true);

  // main.3: Preencher o campo Telefone com 11992837465
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await agent.execAction("input_text", page, {
      action_data: { kwargs: { text: "11992837465" } },
      locator: "locator('#telefone')",
    });
  }, "Preencher o campo Telefone com 11992837465", 'main.3', '16e83b58-3edb-7c92-509c-e30cb4715c88', true);

  // main.4: Preencher o campo Endereco com Rua dos teste
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await agent.execAction("input_text", page, {
      action_data: { kwargs: { text: "Rua dos teste" } },
      locator: "locator('#endereco')",
    });
  }, "Preencher o campo Endereco com Rua dos teste", 'main.4', '25777e10-311b-815d-bac2-4c209771334e', true);

  // main.5: Enviar o formulario de cadastro de usuario
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await page.getByRole('button', { name: 'Cadastrar Usuário' }).first().click({ timeout: 5000 });
  }, "Enviar o formulario de cadastro de usuario", 'main.5', '8464a05f-617b-3e2f-6991-e87a6093eefd', true);
});